name: delivery
run-name: ${{ github.workflow }} (${{ github.ref_name }} by ${{ github.actor }})
concurrency: ${{ github.workflow }}-${{ github.ref_name }}
on:
  push:
    branches: 
      - main
    tags: 
      - pre-release-**
      - release-**
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
          owner: otakakot
          repositories: otakakot/sample-manifest
      - name: Repository Dispatch
        uses: otakakot/repository-dispatch@v1.0.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: otakakot/sample-manifest
          event-type: ref
          client-payload: '{"ref": "${{ github.ref_name }}"}'
